{"timestamp":"2025-06-05T13:49:57.003958","level":"info","event":"DAG bundles loaded: dags-folder, example_dags","logger":"airflow.dag_processing.bundles.manager.DagBundlesManager"}
{"timestamp":"2025-06-05T13:49:57.004937","level":"info","event":"Filling up the DagBag from /opt/airflow/dags/DAG_oparation.py","logger":"airflow.models.dagbag.DagBag"}
{"timestamp":"2025-06-05T13:49:57.040310Z","level":"info","event":"Task instance is in running state","chan":"stdout","logger":"task"}
{"timestamp":"2025-06-05T13:49:57.040780Z","level":"info","event":" Previous state of the Task instance: TaskInstanceState.QUEUED","chan":"stdout","logger":"task"}
{"timestamp":"2025-06-05T13:49:57.041050Z","level":"info","event":"Current task name:extract_new_data","chan":"stdout","logger":"task"}
{"timestamp":"2025-06-05T13:49:57.041294Z","level":"info","event":"Dag name:worldbank_etl","chan":"stdout","logger":"task"}
{"timestamp":"2025-06-05T13:49:57.048879","level":"info","event":"Arquivo de dados existentes n√£o encontrado. Criando novo com os dados atuais.","logger":"airflow.task"}
{"timestamp":"2025-06-05T13:49:57.050221","level":"error","event":"Task failed with exception","logger":"task","error_detail":[{"exc_type":"OSError","exc_value":"Cannot save file into a non-existent directory: '/opt/airflow/dags/../Transformation/Final_Aggregation/Final_data'","exc_notes":[],"syntax_error":null,"is_cause":false,"frames":[{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":838,"name":"run"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":1130,"name":"_execute_task"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/bases/operator.py","lineno":408,"name":"wrapper"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/operators/python.py","lineno":212,"name":"execute"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/operators/python.py","lineno":235,"name":"execute_callable"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/callback_runner.py","lineno":81,"name":"run"},{"filename":"/opt/airflow/dags/DAG_oparation.py","lineno":124,"name":"extract_new_data"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/pandas/core/generic.py","lineno":3902,"name":"to_csv"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/pandas/io/formats/format.py","lineno":1152,"name":"to_csv"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/pandas/io/formats/csvs.py","lineno":247,"name":"save"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/pandas/io/common.py","lineno":739,"name":"get_handle"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/pandas/io/common.py","lineno":604,"name":"check_parent_directory"}]}]}
{"timestamp":"2025-06-05T13:49:57.076640Z","level":"info","event":"Task instance in failure state","chan":"stdout","logger":"task"}
{"timestamp":"2025-06-05T13:49:57.077082Z","level":"info","event":"Task start","chan":"stdout","logger":"task"}
{"timestamp":"2025-06-05T13:49:57.077342Z","level":"info","event":"Task:<Task(PythonOperator): extract_new_data>","chan":"stdout","logger":"task"}
{"timestamp":"2025-06-05T13:49:57.077611Z","level":"info","event":"Failure caused by Cannot save file into a non-existent directory: '/opt/airflow/dags/../Transformation/Final_Aggregation/Final_data'","chan":"stdout","logger":"task"}
